### ISSUE TITLE
Encode consensus results in a link to frapps interface

### ISSUE THREAD

**Issue by sim31** [fatherabraham-hms/fractalgram#18]
Consensus results can be specified in a URL like so: https://of.frapps.xyz/?groupnumber=1&vote1=0xAED620c450911c38714E666cd84137767e3D6286&vote2=0xBb7F06718882952c2b1062b851197610fF2DA051&vote3=0xC11C6f47fe090a706bA82964B8A98F1682b244Ff

vote1 is the top level (level 6), vote2 is level 5... Same scheme was used in the previous interface for optimism fractal.

This way results do not have to be copied manually.

Alternative is to integrate with ordao directly using orclient.

**Comment by fatherabraham-hms** [comment]
Fixed with PR 19!
![image](https://github.com/user-attachments/assets/313e3202-0b89-41b0-b814-528e0c92f1f8)
